# Generated by Django 5.0.6 on 2024-07-06 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sciences',
            name='directions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sciences', to='main.directions'),
        ),
        migrations.AlterField(
            model_name='sciences',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sciences', to='main.subject'),
        ),
    ]
