# Generated by Django 5.0.6 on 2024-07-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_sciences_directions_alter_sciences_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='directions',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
