# Generated by Django 5.0.6 on 2024-07-06 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_directions_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sciences',
            name='subject',
        ),
        migrations.AddField(
            model_name='sciences',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='sciences',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='main.sciences'),
            preserve_default=False,
        ),
    ]
