# Generated by Django 5.0.6 on 2024-07-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_sciences_subject_sciences_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='video',
        ),
        migrations.AddField(
            model_name='problems',
            name='video',
            field=models.FileField(default=1, upload_to='subject-video'),
            preserve_default=False,
        ),
    ]
