# Generated by Django 5.0.6 on 2024-07-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_subject_video_problems_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
