# Generated by Django 5.0.6 on 2024-07-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_question_category_questionresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresult',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
