# Generated by Django 5.0.6 on 2024-07-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_mainpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='text',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
